version: "3.4"

services:
  retornaJuros:
    container_name: retornajuros
    image: retornaJuros
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
